spring:
  application:
    name: speech-service

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

  servlet:
    multipart:
      max-file-size: 25MB
      max-request-size: 25MB

speech:
  stt:
    mock: true
